update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -627,6 +627,13 @@ ORTED
 EGREP
 GREP
 CPP
+MPICH2VERSION
+OMPI_INFO
+MPICC
+SED
+ORTERUN
+MPIEXEC
+MPIRUN
 OBJEXT
 EXEEXT
 ac_ct_CC
@@ -2079,6 +2086,14 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+R_SCMD="${R_HOME}/bin/Rscript -e"
+
+
 OSTYPE="`uname`"
 
 ## One way is to specify both include and lib paths
@@ -2141,24 +2156,8 @@ else
   fi
 fi
 
-if test -z "${MPI_INCLUDE_PATH}" ; then
-
-## another way is to specify MPI_ROOT, perhaps via --with-mpi
-
-# Check whether --with-mpi was given.
-if test "${with_mpi+set}" = set; then :
-  withval=$with_mpi;    if test "${withval}" != "no"; then
-        MPI_ROOT=${withval}
-        MPI_INCLUDE_PATH="${MPI_ROOT}/include"
-        LDFLAGS="$LDFLAGS -L${withval}/lib"
-        CPPFLAGS="$CPPFLAGS -I${withval}/include"
-    fi
-
-fi
-
 
 CC=`"${R_HOME}/bin/R" CMD config CC`
-CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -2949,9 +2948,404 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 if test "X$CC" = "X" ; then
-# Our best guess...
-CC="gcc -std=gnu99"
+  # Our best guess...
+  CC="gcc -std=gnu99"
 fi
+
+
+# Extract the first word of "mpirun", so it can be a program name with args.
+set dummy mpirun; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_MPIRUN+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$MPIRUN"; then
+  ac_cv_prog_MPIRUN="$MPIRUN" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_MPIRUN="mpirun"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_MPIRUN" && ac_cv_prog_MPIRUN=""F""
+fi
+fi
+MPIRUN=$ac_cv_prog_MPIRUN
+if test -n "$MPIRUN"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $MPIRUN" >&5
+$as_echo "$MPIRUN" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+# Extract the first word of "mpiexec", so it can be a program name with args.
+set dummy mpiexec; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_MPIEXEC+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$MPIEXEC"; then
+  ac_cv_prog_MPIEXEC="$MPIEXEC" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_MPIEXEC="mpiexec"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_MPIEXEC" && ac_cv_prog_MPIEXEC=""F""
+fi
+fi
+MPIEXEC=$ac_cv_prog_MPIEXEC
+if test -n "$MPIEXEC"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $MPIEXEC" >&5
+$as_echo "$MPIEXEC" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+# Extract the first word of "orterun", so it can be a program name with args.
+set dummy orterun; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_ORTERUN+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$ORTERUN"; then
+  ac_cv_prog_ORTERUN="$ORTERUN" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ORTERUN="orterun"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_ORTERUN" && ac_cv_prog_ORTERUN=""F""
+fi
+fi
+ORTERUN=$ac_cv_prog_ORTERUN
+if test -n "$ORTERUN"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ORTERUN" >&5
+$as_echo "$ORTERUN" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+# Extract the first word of "sed", so it can be a program name with args.
+set dummy sed; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_SED+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$SED"; then
+  ac_cv_prog_SED="$SED" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_SED="sed"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_SED" && ac_cv_prog_SED=""F""
+fi
+fi
+SED=$ac_cv_prog_SED
+if test -n "$SED"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $SED" >&5
+$as_echo "$SED" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+# Extract the first word of "mpicc", so it can be a program name with args.
+set dummy mpicc; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_MPICC+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$MPICC"; then
+  ac_cv_prog_MPICC="$MPICC" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_MPICC="mpicc"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_MPICC" && ac_cv_prog_MPICC=""F""
+fi
+fi
+MPICC=$ac_cv_prog_MPICC
+if test -n "$MPICC"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $MPICC" >&5
+$as_echo "$MPICC" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+# Extract the first word of "ompi_info", so it can be a program name with args.
+set dummy ompi_info; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_OMPI_INFO+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$OMPI_INFO"; then
+  ac_cv_prog_OMPI_INFO="$OMPI_INFO" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_OMPI_INFO="ompi_info"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_OMPI_INFO" && ac_cv_prog_OMPI_INFO=""F""
+fi
+fi
+OMPI_INFO=$ac_cv_prog_OMPI_INFO
+if test -n "$OMPI_INFO"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $OMPI_INFO" >&5
+$as_echo "$OMPI_INFO" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+# Extract the first word of "mpich2version", so it can be a program name with args.
+set dummy mpich2version; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_MPICH2VERSION+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$MPICH2VERSION"; then
+  ac_cv_prog_MPICH2VERSION="$MPICH2VERSION" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_MPICH2VERSION="mpich2version"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_MPICH2VERSION" && ac_cv_prog_MPICH2VERSION=""F""
+fi
+fi
+MPICH2VERSION=$ac_cv_prog_MPICH2VERSION
+if test -n "$MPICH2VERSION"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $MPICH2VERSION" >&5
+$as_echo "$MPICH2VERSION" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+
+
+if test -z "${MPI_INCLUDE_PATH}" ; then
+  if test "$MPITYPE" = "UNKNOWN" -o "$MPITYPE" = "OPENMPI" ; then
+    if test "$SED" != "F" -a "$MPICC" != "F" -a "$OMPI_INFO" != "F" ; then
+      echo "found sed, mpicc, and ompi_info ..."
+      TMP_INC="F"
+      TMP_LIB="F"
+
+      TMP_INC_DIRS=`mpicc --showme:incdirs`
+      echo ">> TMP_INC_DIRS = ${TMP_INC_DIRS}"
+
+      TMP_IFS="${IFS}"; IFS=" "
+      for dir in ${TMP_INC_DIRS}; do
+        echo "checking ${dir} ..."
+        if test -f "${dir}/mpi.h" ; then
+          echo "found ${dir}/mpi.h ..."
+          TMP_INC=${dir}
+          break
+        fi
+      done
+      IFS="${TMP_IFS}"
+
+      TMP_LIB_DIRS=`mpicc --showme:libdirs`
+      echo ">> TMP_LIB_DIRS = ${TMP_LIB_DIRS}"
+
+      TMP_IFS="${IFS}"; IFS=" "
+      for dir in ${TMP_LIB_DIRS}; do
+        echo "checking ${dir} ..."
+        if test -f "${dir}/libmpi.so" ; then
+          echo "found ${dir}/libmpi.so ..."
+          TMP_LIB=${dir}
+          break
+        fi
+                if test -f "${dir}/libmpi.dylib" ; then
+          echo "found ${dir}/libmpi.dylib ..."
+          TMP_LIB=${dir}
+          break
+        fi
+      done
+      IFS="${TMP_IFS}"
+
+      if test "${TMP_INC}" != "F" -a "${TMP_LIB}" != "F" ; then
+        echo "found mpi.h and libmpi.so ..."
+        echo ">> TMP_INC = ${TMP_INC}"
+        echo ">> TMP_LIB = ${TMP_LIB}"
+        MPITYPE="OPENMPI"
+        MPI_INCLUDE_PATH="${TMP_INC}"
+        MPI_LIBPATH="${TMP_LIB}"
+      fi
+    fi
+  fi
+fi
+
+
+if test -z "${MPI_INCLUDE_PATH}" ; then
+#  if test "$MPITYPE" = "UNKNOWN" -o "$MPITYPE" = "MPICH2" ; then
+### MPICH2 users have to specify --with-Rmpi-type=MPICH2 to get this.
+  if test "$MPITYPE" = "MPICH2" ; then
+    if test "$SED" != "F" -a "$MPICC" != "F" -a "$MPICH2VERSION" != "F" ; then
+      echo "found sed, mpicc, and mpich2version ..."
+      TMP_INC="F"
+      TMP_LIB="F"
+
+      TMP_CMD=`mpicc -show`
+      echo ">> TMP_CMD = ${TMP_CMD}"
+
+      TMP_IFS="${IFS}"; IFS=" "
+      for dir in ${TMP_CMD}; do
+        dir_inc=`echo ${dir} | sed -e "s/^-I\(.*\)$/\1/"`
+
+        echo "checking ${dir_inc} ..."
+        if test -f "${dir_inc}/mpi.h" ; then
+          echo "found ${dir_inc}/mpi.h ..."
+          TMP_INC=${dir_inc}
+          break
+        fi
+      done
+      IFS="${TMP_IFS}"
+
+      TMP_IFS="${IFS}"; IFS=" "
+      for dir in ${TMP_CMD}; do
+        dir_lib=`echo ${dir} | sed -e "s/^-L\(.*\)$/\1/"`
+
+        echo "checking ${dir_lib} ..."
+        if test -f "${dir_lib}/libmpich.so" ; then
+          echo "found ${dir_lib}/libmpich.so ..."
+          TMP_LIB=${dir_lib}
+          break
+        fi
+                if test -f "${dir_lib}/libmpich.dylib" ; then
+          echo "found ${dir_lib}/libmpich.dylib ..."
+          TMP_LIB=${dir_lib}
+          break
+        fi
+      done
+      IFS="${TMP_IFS}"
+
+      if test "${TMP_INC}" != "F" -a "${TMP_LIB}" != "F" ; then
+        echo "found mpi.h and libmpich.so ..."
+        echo ">> TMP_INC = ${TMP_INC}"
+        echo ">> TMP_LIB = ${TMP_LIB}"
+        MPITYPE="MPICH2"
+        MPI_INCLUDE_PATH="${TMP_INC}"
+        MPI_LIBPATH="${TMP_LIB}"
+      fi
+    fi
+  fi
+fi
+
+
+if test -z "${MPI_INCLUDE_PATH}" ; then
+
+## another way is to specify MPI_ROOT, perhaps via --with-mpi
+
+# Check whether --with-mpi was given.
+if test "${with_mpi+set}" = set; then :
+  withval=$with_mpi;    if test "${withval}" != "no"; then
+        MPI_ROOT=${withval}
+        MPI_INCLUDE_PATH="${MPI_ROOT}/include"
+        LDFLAGS="$LDFLAGS -L${withval}/lib"
+        CPPFLAGS="$CPPFLAGS -I${withval}/include"
+    fi
+
+fi
+
+
 
 if test -z "$MPI_ROOT" ; then
   for d in /opt/lib /usr/lib /usr /usr/local/lib /usr/local \
@@ -3797,13 +4191,6 @@ case "$MPITYPE" in
     ;;
 esac
 
-
-: ${R_HOME=‘R RHOME‘}
-if test -z "${R_HOME}"; then
-  echo "could not determine R_HOME"
-  exit 1
-fi
-R_SCMD="${R_HOME}/bin/Rscript -e"
 
 # Check whether --enable-pbdPROF was given.
 if test "${enable_pbdPROF+set}" = set; then :
